"""add task status

Revision ID: efaa92af2510
Revises: 40bbb4a69425
Create Date: 2023-09-01 14:52:14.029685

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'efaa92af2510'
down_revision = '40bbb4a69425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
