version: "3.8"

services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # volumes:
    #   - pgdata:/var/lib/postgresql/data


  web:
    container_name: ${DOCKERHUB_REPOSITORY_NAME}_backend
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY_NAME}
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_ECHO=${DB_ECHO}
      - SECRET_KEY=${SECRET_KEY}
      - PROJECT_NAME=${PROJECT_NAME}
      - PROJECT_VERSION=${PROJECT_VERSION}
      - JWT_LIFETIME_SECONDS=${JWT_LIFETIME_SECONDS}
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

# volumes:
#   pgdata:
