"""add workspace foreign key to tasks table

Revision ID: cb5dbdc2773e
Revises: 3d88db75a141
Create Date: 2023-11-15 09:38:47.974152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5dbdc2773e'
down_revision: Union[str, None] = '3d88db75a141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('workspace_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'workspace_id')
    # ### end Alembic commands ###
