"""add creators and executors to tasks table

Revision ID: 531e446eb4f5
Revises: 9a0f64982366
Create Date: 2023-11-14 17:51:54.976451

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '531e446eb4f5'
down_revision: Union[str, None] = '9a0f64982366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator_id', sa.Uuid(), nullable=False))
    op.add_column('tasks', sa.Column('executor_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['executor_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'executor_id')
    op.drop_column('tasks', 'creator_id')
    # ### end Alembic commands ###
