"""add description column to workspace table

Revision ID: a2efb925de75
Revises: cb5dbdc2773e
Create Date: 2024-02-05 17:48:33.761475

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a2efb925de75"
down_revision: Union[str, None] = "cb5dbdc2773e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tasks_creator_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["creator_id"], ["id"], ondelete="RESTRICT"
    )
    op.add_column(
        "workspace_user_association",
        sa.Column(
            "user_role",
            sa.Enum("admin", "user", "reader", name="grouprole"),
            server_default="user",
            nullable=False,
        ),
    )
    op.drop_column("workspace_user_association", "role")
    op.add_column("workspaces", sa.Column("description", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "description")
    op.add_column(
        "workspace_user_association",
        sa.Column(
            "role",
            postgresql.ENUM("admin", "user", "reader", name="grouprole"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("workspace_user_association", "user_role")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_creator_id_fkey",
        "tasks",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
