"""make workspace description optonal

Revision ID: d4830b3054f4
Revises: a2efb925de75
Create Date: 2024-02-07 12:39:08.590023

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4830b3054f4"
down_revision: Union[str, None] = "a2efb925de75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workspaces", "description", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workspaces", "description", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
