"""add time created, uuid not null

Revision ID: 40bbb4a69425
Revises: a6957923b54d
Create Date: 2023-08-30 15:05:03.867106

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '40bbb4a69425'
down_revision = 'a6957923b54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('time_created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_task_time_created'), 'task', ['time_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_time_created'), table_name='task')
    op.drop_column('task', 'time_created')
    # ### end Alembic commands ###
