"""uuid

Revision ID: 42046c936a39
Revises: aafa7b44b652
Create Date: 2023-08-27 14:39:38.158051

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '42046c936a39'
down_revision = 'aafa7b44b652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_index('ix_task_id', table_name='task')
    op.drop_index('ix_task_year', table_name='task')
    op.create_index(op.f('ix_task_uuid'), 'task', ['uuid'], unique=False)
    op.drop_column('task', 'year')
    op.drop_column('task', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_task_uuid'), table_name='task')
    op.create_index('ix_task_year', 'task', ['year'], unique=False)
    op.create_index('ix_task_id', 'task', ['id'], unique=False)
    op.drop_column('task', 'uuid')
    # ### end Alembic commands ###
