"""year

Revision ID: aafa7b44b652
Revises: fcb16131a70a
Create Date: 2023-08-27 14:20:33.809537

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'aafa7b44b652'
down_revision = 'fcb16131a70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_year'), 'task', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_year'), table_name='task')
    op.drop_column('task', 'year')
    # ### end Alembic commands ###
