"""init

Revision ID: fcb16131a70a
Revises: 
Create Date: 2023-08-27 14:18:06.730759

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcb16131a70a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.Integer(), nullable=True))
    op.drop_index('ix_task_uuid', table_name='task')
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.drop_column('task', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.create_index('ix_task_uuid', 'task', ['uuid'], unique=False)
    op.drop_column('task', 'id')
    # ### end Alembic commands ###
